name: Feature Request
description: 新機能/改善の要望チケット
title: '[Feature]: '
labels: ['type:feature', 'area:infra']
body:
  - type: textarea
    id: background
    attributes:
      label: 背景/目的（なぜ必要か）
      description: ユースケース/課題/SLO/セキュリティ根拠など1-3行で
      placeholder: 例) ECSサービスのスケール時にCPU 80%超が10分続く。自動スケールでSLOを守るため。
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: 要件/スコープ（何を変えるか）
      description: 変更対象（サービス/リソース/設定）と非対象
      placeholder: 例) 対象: ecs_service/api のASG/TargetTracking。非対象: DB, VPC。
    validations:
      required: true

  - type: dropdown
    id: risk
    attributes:
      label: リスクレベル
      options:
        - Low
        - Medium
        - High
    validations:
      required: true

  - type: dropdown
    id: cost
    attributes:
      label: コスト影響
      options:
        - なし
        - 小（~¥1,000/月）
        - 中（~¥10,000/月）
        - 大（>¥10,000/月）
    validations:
      required: true
