name: Feature Request
description: 新機能/改善の要望チケット
title: '[Feature]: '
labels: ['type:feature', 'area:infra']
body:
  - type: textarea
    id: background
    attributes:
      label: 背景/目的
      description: なぜ必要か
      placeholder: 例) README.mdにGitHub運用セクション追加
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: 要件/スコープ
      description: 何を変えるか
      placeholder: 例) README.mdの最後にGitHub運用セクション追加
    validations:
      required: true

  - type: checkboxes
    id: acceptance
    attributes:
      label: 受け入れ条件
      options:
        - label: テスト通過
        - label: ドキュメント更新
    validations:
      required: true

  - type: dropdown
    id: downtime
    attributes:
      label: ダウンタイム
      options:
        - なし
        - あり
    validations:
      required: true

  - type: dropdown
    id: risk
    attributes:
      label: リスクレベル
      options:
        - Low
        - Medium
        - High
    validations:
      required: true

  - type: dropdown
    id: cost
    attributes:
      label: コスト影響
      options:
        - なし
        - 小
        - 中
        - 大
    validations:
      required: true
