name: Feature Request
description: 新機能の提案
title: '[Feature]: '
labels: ['enhancement']
body:
  - type: textarea
    id: description
    attributes:
      label: 説明
      description: 何を実装したいか
    validations:
      required: true
