name: Feature Request
description: 新機能/改善の要望チケット
title: '[Feature]: 短い要約（例: README.mdにGitHub運用セクション追加）'
labels: ['type:feature', 'area:infra', 'risk:low', 'cost:none']
body:
  - type: dropdown
    id: type
    attributes:
      label: 種別
      options:
        - Feature
        - Fix
        - Docs
        - Infra
        - Security
        - Chore
    validations:
      required: true

  - type: textarea
    id: background
    attributes:
      label: 背景/目的
      description: なぜ必要か
      placeholder: 例) README.mdにGitHub運用セクション追加
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: 要件/スコープ
      description: 何を変えるか
      placeholder: 例) README.mdの最後にGitHub運用セクション追加
    validations:
      required: true

  - type: checkboxes
    id: acceptance
    attributes:
      label: 受け入れ条件
      options:
        - label: テスト通過
        - label: ドキュメント更新
        - label: 監視/アラート更新
        - label: セキュリティ/ポリシー確認
    validations:
      required: true

  - type: dropdown
    id: downtime
    attributes:
      label: ダウンタイム
      options:
        - なし
        - あり
    validations:
      required: true

  - type: textarea
    id: downtime_detail
    attributes:
      label: ダウンタイム詳細（必要時）
      placeholder: 例) メンテ窓 02:00-02:10
    validations:
      required: false

  - type: dropdown
    id: risk
    attributes:
      label: リスクレベル
      options:
        - Low
        - Medium
        - High
    validations:
      required: true

  - type: textarea
    id: risk_reason
    attributes:
      label: リスク根拠（Medium/High時）
      placeholder: 例) 本番ネットワーク経路変更
    validations:
      required: false

  - type: dropdown
    id: cost
    attributes:
      label: コスト影響
      options:
        - なし
        - 小
        - 中
        - 大
    validations:
      required: true

  - type: textarea
    id: cost_basis
    attributes:
      label: コスト根拠（必要時）
      placeholder: 例) NAT GW追加 0.062 USD/時
    validations:
      required: false

  - type: checkboxes
    id: links
    attributes:
      label: 連携
      options:
        - label: ブランチ命名にIssue番号を含める
        - label: PR本文にCloses記載
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: 補足
      placeholder: 既知の制約や代替案
    validations:
      required: false
