# セキュリティスキャン統合ワークフロー
# 目的: 依存関係、コンテナ、コード、IaC、シークレットの脆弱性を一元管理

name: Security Scan
on:
  workflow_dispatch:
    # 手動実行のみ許可（PRやスケジュールでは実行されない）
  # pull_request:
  #   branches: [main, feature/develop]
  # schedule:
  #   - cron: "0 0 * * 1"
jobs:
  dependency-scan:
    name: Dependency Vulnerability Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner (npm)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH"
      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: "trivy-results.sarif"
  container-scan:
    name: Container Image Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: nestjs-hannibal-3:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true
      - name: Run Trivy vulnerability scanner (Docker)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "nestjs-hannibal-3:${{ github.sha }}"
          format: "sarif"
          output: "trivy-container-results.sarif"
          severity: "CRITICAL,HIGH"
      - name: Upload Trivy container results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: "trivy-container-results.sarif"
  sast-scan:
    name: Static Application Security Testing
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript-typescript
      - name: Autobuild
        uses: github/codeql-action/autobuild@v3
  summary:
    name: Security Scan Summary
    runs-on: ubuntu-latest
    needs:
      - dependency-scan
      - container-scan
      - sast-scan
    if: always()
    steps:
      - name: Check scan results
        run: |
          echo "## Security Scan Results" >> $GITHUB_STEP_SUMMARY
          echo "- Dependency Scan: ${{ needs.dependency-scan.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- Container Scan: ${{ needs.container-scan.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- SAST Scan: ${{ needs.sast-scan.result }}" >> $GITHUB_STEP_SUMMARY
          echo "詳細は [Security > Code scanning alerts](../../security/code-scanning) を確認" >> $GITHUB_STEP_SUMMARY
